config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  resources :events do
    resources :registrations
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy


  validates :name, :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { only_integer: true, greater_than: 0}

  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }


  # all business logic in model
  def free?
    price.blank? || price.zero?
  end

  def self.upcoming
    where("starts_at >=?", Time.now).order("starts_at")
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event


  validates :name, presence: true

  validates :email, format: { with: /(\S+)@(\S+)/ }

  HOW_HEARD_OPTIONS = [
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]
  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :error
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    # @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, success: "Event successfully updated!"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, success: "Event successfully created!"
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, error: "Event successfully deleted!"
  end

private

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @registrations = @event.registrations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free!")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3"><br>
      <%= form_for(@event) do |f| %>
        <%= render "shared/errors" %>

        <!-- Event Details -->
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :name, "Event title" %>
              <%= f.text_field :name, placeholder: "Add a short, clear name", class: "form-control", autofocus: true %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :location %>
              <%= f.text_field :location, placeholder: "Include a place or address", class: "form-control" %>
            </div>
          </div>
        </div>

        <!-- fix this later -->
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :starts_at, "Starts" %>

              <%= f.datetime_field :starts_at, class: "form-control" %>

              <!-- Splitting date and time -->
              <!-- <%= f.date_field :starts_at, class: "form-control", value: Date.today %> -->
              <!-- <%= f.time_field :starts_at, class: "form-control" %> -->
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :image_file_name, "Event Image" %>
              <%= f.text_field :image_file_name, placeholder: "Add event image", class: "form-control", size: 30 %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, placeholder: "Tell people about the event", class: "form-control", rows: 5 %>
            </div>
          </div>
        </div>


        <!-- Create Tickets -->
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :price %>
              <%= f.number_field :price, placeholder: "15.00", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :capacity %>
              <%= f.number_field :capacity, placeholder: "100", class: "form-control" %>
            </div>
          </div>
        </div>

        <br>

        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", events_path, class: "btn btn-default" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Event: <%= @event.name %></h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<!-- Bootstrap grid -->
<% @events.each do |event| %>
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-md-offset-6">
        <h2><%= link_to(event.name, event) %></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 col-md-offset-3">
        <%= image_for(event) %>
      </div>

      <div class="col-md-3">
        <h3><%= pluralize(event.capacity, 'spot') %> available </h3>
        <p><%= truncate(event.description, length: 40, separator: ' ') %></p>
        <p>When: <%= event.starts_at.to_s %></p>
        <p>Where: <%= event.location %></p>
        <p>Price: <%= format_price(event) %></p>
      </div>
    </div>
  </div>

<% end %>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Create Event</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1><%= @event.name %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <%= image_for(@event) %>
    </div>

    <div class="col-md-9">
      <h2><%= @event.starts_at %></h2>
      <p><%= @event.description %></p>

      <div class="row">
        <div class="col-md-12">
          <h3>Price</h3><hr>
          <p><%= format_price(@event) %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h3>Location</h3><hr>
          <p><%= @event.location %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h3>Capacity</h3><hr>
          <p><%= pluralize(@event.capacity, 'spot') %></p>
        </div>
      </div>
      <br>

      <div class="actions">
        <%= link_to "Who's Registered?", event_registrations_path(@event) %>
      </div>
      <br>

      <div class="actions">
        <%= link_to "Edit", edit_event_path(@event), class: "btn btn-primary" %>
        <%= link_to "Delete", event_path(@event), class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p>Copyright &copy; 2017</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Events</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'All Events', root_path %></li>
        <li><%= link_to 'Add New Event', new_event_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "layouts/navbar" %>

  <%= render "shared/flashes" %>

  <%= yield %>

  <%= render "layouts/footer" %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <header>
      <h2>Oops! The <%= @event.class.name.titleize.downcase %> could not be saved</h2>
      <h3>Please correct the following <%= pluralize(@event.errors.count, "error") %>:</h3>
    </header>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>